"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Crosshair, MapPin, Package, Search, ShieldCheck, Tag, UserRound } from "lucide-react";
import { api } from "@/lib/api";
import LocationVerification from "@/components/locations/LocationVerification";

const money=(n)=>`RWF ${new Intl.NumberFormat("en-RW",{maximumFractionDigits:0}).format(Number(n||0))}`;
const quoteInputs=["sender_name","sender_phone","recipient_name","recipient_phone","pickup_address","pickup_city","pickup_lat","pickup_lng","pickup_notes","delivery_address","delivery_city","delivery_lat","delivery_lng","delivery_notes","parcel_description","parcel_category","parcel_weight_kg","parcel_declared_value","is_fragile","discount_code"];
const SAME_LOCATION_THRESHOLD_KM=0.05;

function haversineKm(lat1,lng1,lat2,lng2){
 const toRad=v=>v*Math.PI/180;
 const dLat=toRad(lat2-lat1),dLng=toRad(lng2-lng1);
 const a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLng/2)**2;
 return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));
}

function locationDistanceKm(a,b){
 const lat1=Number(a?.lat),lng1=Number(a?.lng),lat2=Number(b?.lat),lng2=Number(b?.lng);
 if(![lat1,lng1,lat2,lng2].every(Number.isFinite))return null;
 return haversineKm(lat1,lng1,lat2,lng2);
}

function LocationBox({label,value,onChange,onSelect,onCurrent,disabled,deviceLocation}){
 const [results,setResults]=useState([]); const [busy,setBusy]=useState(false); const [locked,setLocked]=useState(false);
 useEffect(()=>{if(locked)return;const q=value.trim();if(q.length<2){setResults([]);return}const t=setTimeout(async()=>{setBusy(true);try{const r=await api.searchLocations(q,deviceLocation?.lat,deviceLocation?.lng);setResults(Array.isArray(r?.data||r)?(r?.data||r):[])}catch{setResults([])}finally{setBusy(false)}},300);return()=>clearTimeout(t)},[value,deviceLocation?.lat,deviceLocation?.lng,locked]);
 return <div className="location-box"><label>{label} *</label><div className="input-with-icon"><Search size={17}/><input disabled={disabled} value={value} onChange={e=>{setLocked(false);onChange(e.target.value)}} placeholder="Search a Peleka location or address" autoComplete="off"/></div><button type="button" className="current-location" disabled={disabled} onClick={()=>{setLocked(true);onCurrent()}}><Crosshair size={15}/> Use my current location</button>{!locked&&(busy||results.length>0)&&<div className="location-results">{busy?<div className="location-result-message">Searching…</div>:results.slice(0,8).map((p,i)=><button type="button" key={p.place_id||p.id||i} onClick={()=>{setLocked(true);setResults([]);onSelect(p)}}><MapPin size={15}/><span><strong>{p.name||p.address||"Location"}</strong><small>{[p.sector,p.district,p.city,p.address].filter(Boolean).join(" · ")}</small></span></button>)}</div>}</div>
}

export default function GuestShip(){
 const [form,setForm]=useState({guest_name:"",guest_phone:"",guest_email:"",sender_name:"",sender_phone:"",recipient_name:"",recipient_phone:"",pickup_address:"",pickup_city:"",pickup_lat:null,pickup_lng:null,pickup_notes:"",delivery_address:"",delivery_city:"",delivery_lat:null,delivery_lng:null,delivery_notes:"",parcel_description:"",parcel_category:"",parcel_weight_kg:1,parcel_declared_value:"",is_fragile:false,discount_code:""});
 const [quote,setQuote]=useState(null),[quoteKey,setQuoteKey]=useState(""),[busy,setBusy]=useState(false),[quoteBusy,setQuoteBusy]=useState(false),[message,setMessage]=useState(""),[deviceLocation,setDeviceLocation]=useState(null),[verification,setVerification]=useState(null);
 const seq=useRef(0); const key=useMemo(()=>JSON.stringify(quoteInputs.reduce((a,k)=>(a[k]=form[k],a),{})),[form]);
 const ready=[form.pickup_lat,form.pickup_lng,form.delivery_lat,form.delivery_lng].every(v=>Number.isFinite(Number(v)));
 const routeDistanceKm=useMemo(()=>ready?haversineKm(Number(form.pickup_lat),Number(form.pickup_lng),Number(form.delivery_lat),Number(form.delivery_lng)):null,[form.pickup_lat,form.pickup_lng,form.delivery_lat,form.delivery_lng,ready]);
 const sameLocation=routeDistanceKm!==null&&routeDistanceKm<=SAME_LOCATION_THRESHOLD_KM;
 function invalidateQuote(){seq.current+=1;setQuote(null);setQuoteKey("")} 
 function set(k,v){setForm(f=>({...f,[k]:v}));invalidateQuote();setMessage("")}
 useEffect(()=>{if(navigator.geolocation)navigator.geolocation.getCurrentPosition(p=>setDeviceLocation({lat:p.coords.latitude,lng:p.coords.longitude}),()=>{}, {maximumAge:300000,timeout:7000})},[]);
 function candidateTooClose(prefix,lat,lng){
   const otherPrefix=prefix==="pickup"?"delivery":"pickup";
   const distance=locationDistanceKm({lat,lng},{lat:form[otherPrefix+"_lat"],lng:form[otherPrefix+"_lng"]});
   return distance!==null&&distance<=SAME_LOCATION_THRESHOLD_KM;
 }
 function select(prefix,p){const lat=Number(p.lat??p.latitude),lng=Number(p.lng??p.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng)){setMessage("Please choose a location with valid coordinates.");return}if(candidateTooClose(prefix,lat,lng)){setMessage("Pickup and delivery locations must be at least 50 m apart. Please choose a different location.");return}setVerification({prefix,label:prefix==="pickup"?"Pickup location":"Delivery location",candidate:{...p,lat,lng},inputText:form[prefix+"_address"]||p.address||p.name||""})}
 function confirm(prefix,p){
   const lat=Number(p.lat??p.latitude),lng=Number(p.lng??p.longitude);
   if(!Number.isFinite(lat)||!Number.isFinite(lng)){setMessage("Please confirm a location with valid coordinates.");return}
   if(candidateTooClose(prefix,lat,lng)){setMessage("Pickup and delivery locations must be at least 50 m apart. Please choose a different location.");return}
   invalidateQuote();setForm(f=>({...f,[prefix+"_address"]:p.address||p.formatted_address||p.name||f[prefix+"_address"],[prefix+"_city"]:p.city||p.district||"",[prefix+"_lat"]:lat,[prefix+"_lng"]:lng}));setVerification(null);setMessage("")
 }
 async function current(prefix){if(!navigator.geolocation){setMessage("Location access is unavailable.");return}setBusy(true);navigator.geolocation.getCurrentPosition(async pos=>{try{const r=await api.reverseLocation(pos.coords.latitude,pos.coords.longitude),p=r?.data||r||{};const candidate={...p,lat:pos.coords.latitude,lng:pos.coords.longitude};if(candidateTooClose(prefix,candidate.lat,candidate.lng)){setMessage("Pickup and delivery locations must be at least 50 m apart. Please choose a different location.");return}setVerification({prefix,label:prefix==="pickup"?"Pickup location":"Delivery location",candidate,inputText:p.address||p.display_name||"Current location"})}catch(e){setMessage(e.message||"Unable to identify your location.")}finally{setBusy(false)}},()=>{setBusy(false);setMessage("Please allow location access or search for the location.")},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
 async function getQuote(k=key){if(!ready||sameLocation){if(sameLocation)setMessage("Pickup and delivery locations must be at least 50 m apart. Please choose a different location.");return}const n=++seq.current;setQuoteBusy(true);try{const r=await api.quote({pickup_lat:Number(form.pickup_lat),pickup_lng:Number(form.pickup_lng),delivery_lat:Number(form.delivery_lat),delivery_lng:Number(form.delivery_lng),pickup_city:form.pickup_city||undefined,delivery_city:form.delivery_city||undefined,discount_code:form.discount_code.trim()||undefined});if(n===seq.current){setQuote(r?.data||r);setQuoteKey(k);setMessage("")}}catch(e){if(n===seq.current){setQuote(null);setQuoteKey("");setMessage(e.message||"Unable to calculate the quote.")}}finally{if(n===seq.current)setQuoteBusy(false)}}
 useEffect(()=>{if(!ready||sameLocation)return;const t=setTimeout(()=>getQuote(key),500);return()=>clearTimeout(t)},[key,ready,sameLocation]);
 function validate(){for(const [k,l] of [["guest_name","Your name"],["guest_phone","Your phone"],["sender_name","Sender name"],["sender_phone","Sender phone"],["recipient_name","Recipient name"],["recipient_phone","Recipient phone"],["parcel_description","Parcel description"]])if(!String(form[k]||"").trim())return l+" is required.";if(!ready)return"Confirm both pickup and delivery locations.";if(sameLocation)return"Pickup and delivery locations must be at least 50 m apart. Please choose a different location.";if(Number(form.parcel_weight_kg)<=0)return"Parcel weight must be greater than 0 kg.";return null}
 async function create(){const e=validate();if(e){setMessage(e);return}if(!quote||quoteKey!==key){await getQuote(key);return}setBusy(true);try{const r=await api.createGuestShipment({...form,parcel_weight_kg:Number(form.parcel_weight_kg),parcel_declared_value:form.parcel_declared_value===""?undefined:Number(form.parcel_declared_value),discount_code:form.discount_code.trim()||undefined});const s=r?.data||r;sessionStorage.setItem("peleka_guest_shipment",JSON.stringify({id:s.id,tracking_number:s.tracking_number,guest_access_token:s.guest_access_token,total_price:s.total_price}));window.location.href="/guest-shipment/payment"}catch(e){setMessage(e.message||"Unable to create shipment.")}finally{setBusy(false)}}
 return <main className="guest-checkout"><header className="guest-header"><Link href="/" className="guest-brand">PELEKA<span>.</span></Link><div className="guest-header-right"><span className="guest-secure"><ShieldCheck size={15}/> Secure checkout</span><Link href="/login" className="guest-signin">Sign in</Link></div></header><div className="guest-hero"><div className="guest-hero-copy"><Link href="/" className="back-link"><ArrowLeft size={15}/> Back to Peleka</Link><div className="guest-eyebrow"><span>GUEST SHIPPING</span><i>•</i><span>No account required</span></div><h1>Send it. We’ll <em>take it there.</em></h1><p>Book a pickup, get your price upfront, and pay securely with Mobile Money — all without creating an account.</p></div><div className="guest-steps"><div className="guest-step active"><b>1</b><span>Shipment</span></div><div className="guest-step-line"/><div className="guest-step"><b>2</b><span>Payment</span></div><div className="guest-step-line"/><div className="guest-step"><b>3</b><span>Track</span></div></div></div><div className="form-layout"><div className="form-main">
 <section className="panel form-section"><div className="form-section-head"><div className="form-icon"><ShieldCheck size={19}/></div><div><h2>Your contact</h2><p>We'll use this to give you access to your shipment.</p></div></div><div className="two-col"><Field required label="Your name" value={form.guest_name} onChange={v=>set("guest_name",v)}/><Field required label="Your phone" type="tel" value={form.guest_phone} onChange={v=>set("guest_phone",v)}/><Field label="Email address" type="email" value={form.guest_email} onChange={v=>set("guest_email",v)}/></div></section>
 <section className="panel form-section"><div className="form-section-head"><div className="form-icon"><MapPin size={19}/></div><div><h2>Route</h2><p>Choose a Peleka location or search an address.</p></div></div><LocationBox label="Pickup location" value={form.pickup_address} onChange={v=>{setForm(f=>({...f,pickup_address:v,pickup_lat:null,pickup_lng:null,pickup_city:""}));setQuote(null);setQuoteKey("")}} onSelect={p=>select("pickup",p)} onCurrent={()=>current("pickup")} disabled={busy} deviceLocation={deviceLocation}/><LocationBox label="Delivery location" value={form.delivery_address} onChange={v=>{setForm(f=>({...f,delivery_address:v,delivery_lat:null,delivery_lng:null,delivery_city:""}));setQuote(null);setQuoteKey("")}} onSelect={p=>select("delivery",p)} onCurrent={()=>current("delivery")} disabled={busy} deviceLocation={deviceLocation}/><div className="two-col"><Field label="Pickup notes" value={form.pickup_notes} onChange={v=>set("pickup_notes",v)}/><Field label="Delivery notes" value={form.delivery_notes} onChange={v=>set("delivery_notes",v)}/></div></section>
 <section className="panel form-section"><div className="form-section-head"><div className="form-icon"><UserRound size={19}/></div><div><h2>People</h2><p>Sender and recipient details.</p></div></div><div className="two-col"><Field required label="Sender name" value={form.sender_name} onChange={v=>set("sender_name",v)}/><Field required label="Sender phone" type="tel" value={form.sender_phone} onChange={v=>set("sender_phone",v)}/><Field required label="Recipient name" value={form.recipient_name} onChange={v=>set("recipient_name",v)}/><Field required label="Recipient phone" type="tel" value={form.recipient_phone} onChange={v=>set("recipient_phone",v)}/></div></section>
 <section className="panel form-section"><div className="form-section-head"><div className="form-icon"><Package size={19}/></div><div><h2>Parcel</h2><p>Basic information for the rider.</p></div></div><div className="two-col"><Field required label="Description" value={form.parcel_description} onChange={v=>set("parcel_description",v)}/><Field label="Category" value={form.parcel_category} onChange={v=>set("parcel_category",v)}/><Field required label="Weight (kg)" type="number" min="0.01" step="0.01" value={form.parcel_weight_kg} onChange={v=>set("parcel_weight_kg",v)}/><Field label="Declared value (RWF)" type="number" min="0" value={form.parcel_declared_value} onChange={v=>set("parcel_declared_value",v)}/></div><label className="check-row"><input type="checkbox" checked={form.is_fragile} onChange={e=>set("is_fragile",e.target.checked)}/><span><strong>Fragile parcel</strong><small>We'll flag this shipment for careful handling.</small></span></label></section>
 </div><aside className="quote-side"><div className="guest-trust-strip"><div><ShieldCheck size={17}/><span><strong>Secure checkout</strong><small>Your guest access is protected.</small></span></div><div><Package size={17}/><span><strong>Track every step</strong><small>Get a tracking number after payment.</small></span></div></div><div className="panel quote-panel"><div className="section-kicker">LIVE DELIVERY QUOTE</div><h2>Your price</h2>{quote?<><div className="quote-total"><small>TOTAL</small><strong>{money(quote.total_price)}</strong></div><div className="quote-lines"><span>Distance <b>{Number(quote.distance_km||0).toFixed(2)} km</b></span><span>Driving time <b>{Number(quote.duration_minutes||0)} min</b></span><span>Subtotal <b>{money(quote.subtotal)}</b></span></div></>:<div className="quote-placeholder"><Tag size={22}/><span>{sameLocation?"Choose pickup and delivery locations at least 50 m apart.":ready?"Calculating your quote…":"Confirm both locations to see your price."}</span></div>}<Field label="Discount code" value={form.discount_code} onChange={v=>set("discount_code",v)}/><button type="button" className="button button-orange full" onClick={create} disabled={busy||quoteBusy||!quote||quoteKey!==key}>{busy?"Creating shipment…":quoteBusy?"Updating quote…":"Continue to payment"}<ArrowRight size={16}/></button>{message&&<div className="form-error">{message}</div>}<p className="guest-login-note">Already have a Peleka account? <Link href="/login">Sign in</Link></p></div></aside></div><footer className="guest-footer"><span>© {new Date().getFullYear()} Peleka</span><span>Fast, reliable delivery in Rwanda</span><Link href="/privacy-policy">Privacy</Link></footer>{verification&&<LocationVerification open label={verification.label} candidate={verification.candidate} inputText={verification.inputText} locationType={verification.prefix} onCancel={()=>setVerification(null)} onConfirm={p=>confirm(verification.prefix,p)}/>}</main>
}
function Field({label,value,onChange,placeholder,type="text",required=false,min,step}){return <label className="field"><span>{label}{required?" *":""}</span><input type={type} value={value??""} onChange={e=>onChange(e.target.value)} placeholder={placeholder||""} required={required} min={min} step={step}/></label>}
